name: dbt CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dbt
        run: pip install dbt-core dbt-duckdb

      - name: Install dbt packages
        run: dbt deps
        env:
          DBT_PROFILES_DIR: .

      - name: Seed raw data
        run: dbt seed
        env:
          DBT_PROFILES_DIR: .


      - name: Run dbt build
        run: dbt build
        env:
          DBT_PROFILES_DIR: .
